apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.config.name }}
  labels:
    app: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
data:
 {{- range .Values.app.config.data }}
  {{ .key }}: {{ quote .value }}
 {{- end}}
