apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}
  type: {{ .Values.app.service.type }}
  ports:
   - protocol: {{ .Values.app.service.protocol }}
     port: {{ .Values.app.service.port }}
     targetPort: {{ .Values.app.service.targetPort }}
